### ISSUE TITLE
OOPをC言語で設計

### ISSUE THREAD

**Issue by blmd-niz** [takehira/BLMD_TSK#1]
## 概要
基本的にソフトウェア開発はオブジェクト指向で、機能モジュールの再利用を前提とした開発をしています。
その際に、ペリフェラルや外付けデバイスに対応した制御クラスの設計が必要になるケースがそれなりに発生します。
さて、C++が使えるケースは多いのですが、最近は逆にコストダウンのため8ビット品なども使い始める予定で、そのときC言語でプログラミングすることになります。

そこで、OOPのパラダイム、かつC言語での設計を併せた課題について考えてみてもらえないでしょうか。

## 詳細要件
1. 2入力のint変数を演算してintの結果を返す2つのメソッドpre_calc, post_calcを備えるインターフェイスクラスIAlgoを定義する。
2. 次のクラスを定義する。
クラスAlgo1は、入力の足し算を行うpre_calcと引き算を行うpost_calcを備える。
クラスAlgo2は、入力の引き算を行うpre_calcとかけ算を行うpost_calcを備える。
3. Factory関数を実装して下さい。一つのint引数を取り、0であればAlgo1、1であればAlgo2を生成して下さい。
動的な生成、静的な生成どちらでも構いません。
※とても小さいメモリやその他リソースしか使えないデバイスを想定して頂けるようであればベストです。
4. Algo_calc関数を実装して下さい。一つのIAlgoインターフェイスと2つのint値を引数にとり、
post_calc(pre_calc(入力1, 入力2), 定数100)のint演算結果を返す。
5. main関数でFactory関数を使ってAlgo1、Algo2どちらのオブジェクトも生成し、
それぞれの演算結果を表示するように実装して下さい。

## 補足
- 最近共通開発プラットフォームをリニューアルしています。この課題は、直近の設計で必要になったことを含む内容になっています。
- C言語だけで実装することは生産性に退行するようですが、実際に必要になっていること、その上で生産性のあるパラダイムを使う考え方で進めていることをお伝えできればと考えました。
- 設計例が必要になったときにはご遠慮無く御連絡下さい。

どうぞお気軽に、お時間が取れたときよろしくお願い致します。

**Comment by takehira** [comment]
太田です。
自己都合ですが、引越し先の内見やアドバンスドコーヒーマイスター受験で、なかなか取り組む時間が作れず進捗が乏しい状況です。
時間が空いてしまっているので、まずはレスポンスさせていただきました。

引越し先は決めましたが、各種書類の準備や引越し業者の見積もり・打ち合わせ等で休日の時間が取られそうです。

**Comment by blmd-niz** [comment]
状況御連絡ありがとうございます、了解いたしました。
実際の作業をすると時間が取られると思います。キッチン家電系の設計で、OOPなどは必要なものの、このくらいローレベルに実装されている部分もあるので、というご理解を頂ければまずは良いのかと思います。
その上でご準備可能でしたら幸いです。
色々と異動のご準備等大変な案件の優先度低の一つとして捉えて下さい。
以上暑くなってきましたし、どうぞほどほどに!

**Comment by takehira** [comment]
ご配慮ありがとうございます。[課題コード](https://github.com/takehira/BLMD_TSK/tree/master/OOP_on_C)をコミットしました。

コードの通りですが、以下簡単な説明です。
・Algo.hでインターフェースクラスlAlgoを定義
・Algo1.h, Algo2.hでAlgo1,2クラスのメソッドを定義
・main.cにFactory, Algo_calc関数を実装

関数ポインタの構造体をnew_Algo*というマクロにすることで、C++ライクに記述出来るようにしました。

**Comment by blmd-niz** [comment]
お忙しい中ご対応お疲れ様でした。
基本的には申し分ございません。
ただ、単純な問題がありまして、そこだけ今後の課題ですかね。
詳しくはPull requestにまとめました。

**Comment by takehira** [comment]
レビューありがとうございました。
macOSでの動作は未確認でした、、うかつでした。
Windows10上のVirtualBoxで動かしているUbuntu14で開発していましたが、こちらではSegmentation Faultは発生せず、期待通りの動作をしていました。実行系(コンパイラ)に依存するかもしれませんが、ご指摘いただいた通り、そもそも元々のコードの変数の使い方がよくありませんでした。修正前のコードでUbuntu上どうなるか、同様にアドレスを確認してみたいと思います。

**Comment by takehira** [comment]
# intel Mac以外の動作確認
## Ubuntu 14 (on VirtualBox)
修正前のコード
```Ubuntu Old
@Factory algo: 0x4006f8 0x40070c
@Factory algo: 0x400722 0x400738
@main.algo1: 0x4006f8 0x40070c
@main.test1: 0x4006f8 0x40070c
@main.test1.pre_calc(100, 200): 300
@main.test1.post_calc(100, 200): -100
algo1: -70
algo2: -1000
```
修正後のコード
```Ubuntu New
@Factory algo: 0x400718 0x40072c
@Factory algo: 0x400742 0x400758
@main.algo1: 0x400718 0x40072c
@main.test1: 0x400718 0x40072c
@main.test1.pre_calc(100, 200): 300
@main.test1.post_calc(100, 200): -100
algo1: -70
algo2: -1000
```
修正前、修正後ともFactoryの呼び出しに対して、Algo1, Algo2が別のアドレスで返ってきていました。深く追えていませんがgccの仕様の違いと考えています。

## PowerPC Mac(Powerbook G4)
試しに、古いPowerPCのMacでも試してみました。

修正前のコード
```PowerPC Old
@Factory algo: 0xbffffcdc 0x8
@Factory algo: 0xbffffcdc 0x8
@main.algo1: 0xbffffcdc 0x8
@main.test1: 0x29dc 0x2a0c
@main.test1.pre_calc(100, 200): 300
@main.test1.post_calc(100, 200): -100
Illegal instruction
```
同様に修正前のコードでは止まってしまいます。
intelMac同様にFacroryの2回の呼び出しに対して、同じアドレスが返ってきています。
しかも、post_calcの方はアドレスが変です。

修正後のコード
```PowerPC New
@Factory algo: 0x29dc 0x2a0c
@Factory algo: 0x2a3c 0x2a6c
@main.algo1: 0x29dc 0x2a0c
@main.test1: 0x29dc 0x2a0c
@main.test1.pre_calc(100, 200): 300
@main.test1.post_calc(100, 200): -100
algo1: -70
algo2: -1000
```
こちらは正常動作しています。

# まとめ
{ ]で囲まれた範囲が変数のスコープなので、本来if文の{ }内で宣言したalgoのスコープはif文内でのみ有効。すなわち、ifの前で宣言したlAlgo algoとif文中のlAlgo algoは別物として扱われるはずなので、修正後のコードの書き方がセオリー。

**Comment by blmd-niz** [comment]
お忙しい中すいません、こんなに試していただきまして。
もう十分かと思います。お疲れ様でした。
8月は流石にお忙しいかと思います。
9月にお目にかかるのを一同お待ちしています!

**Comment by takehira** [comment]
承知いたしました、ご配慮ありがとうございます。
そうですね、業務引継ぎが激化してきたのに加え、挨拶回りや引越し準備等で今月はバタバタしそうです。なお、
　8/28 現業の最終出社
　8/29-30 引越し
　8/31 住民票等の手続き
の予定です。
こちらこそ、9月からご一緒させていただけることに改めて身の引き締まる想いです。
よろしくお願いいたします。
